controller_list:
  - name: "/mico_arm/mico_arm_trajectory_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
  - name: /gripper_action_server
    type: GripperCommand
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2
