controller_list:
 - name: mico_arm_driver/joint_trajectory_angles
   action_ns: joint_velocity_controller
   type: FollowJointTrajectory
   default: true
   joints:
     - mico_joint_1
     - mico_joint_2
     - mico_joint_3
     - mico_joint_4
     - mico_joint_5
     - mico_joint_6


